spring.application.name=story-app
spring.datasource.url=jdbc:mysql://localhost:3307/story_app?createDatabaseIfNotExist=true&serverTimezone=Asia/Ho_Chi_Minh

spring.datasource.username=story_user
spring.datasource.password=story123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.upload.audio-dir=uploads/audio
